### PR TITLE
Ab 57 web development express 1.12.3

### PR DESCRIPTION
**Pull request by Vinggio**
### _Ticket_:
https://alebrije-dev.atlassian.net/jira/software/c/projects/AB/boards/27?modal=detail&selectedIssue=AB-57&assignee=62f3c643e50f2f2a3957324e

### _Overview_:
My portfolio with projects, technology knowledges, option to contact and more with basic csv, html and js code

### _What Changed_:
I added my portfolio with its characteristics

### _How To Test_:
Clone the branch and open the ab-57.html file in your browser

### _Evidence_:
Captura desde 2022-08-22 11-28-38

### CODE REVIEW

**Comment by mralebrije** [comment]
https://alebrije-dev.atlassian.net/wiki/spaces/~5f1c8d1b0439d90022cbfe26/pages/4882433/FS+-+Team+Standards#Use-the-ticket-ID-and-ticket-title-in-your-PR-title

**Comment by mralebrije** [comment]
the ticket link mentioned in the PR could be smaller...instead of linking to the entire jira board.

**Comment by mralebrije** [comment]
when i send an invalid email address in the form I get an alert but then I'm redirected to another page... seems the request is bing sent even if the email is incorrect... could u instead avoid this and match the behavior presented in the solution? where the validation error is displayed in the input field?

**Comment by mralebrije** [comment]
can you make the form widhth smaller to have a better readability?

**Comment by mralebrije** [comment]
Nice work

**Review by mralebrije — APPROVED** [review]

**Comment by Vinggio** [comment]
Required changes were applied

**Pull request merged**
